{
    'name': 'Product Expiry Alert Manager',
    'version': '19.0.1.0.0',
    'summary': 'Proactive stock expiry monitoring with colour-coded dashboard and auto alerts',
    'description': """
        Product Expiry Alert Manager monitors lot/serial expiry dates for Odoo 19 CE.
        Features: Traffic-light expiry dashboard, tiered email alerts (30/15/7/3/1 days),
        auto internal transfer to clearance location, FIFO sort helper, weekly digest,
        cost-at-risk report, bulk clearance wizard, and full audit trail.
    """,
    'category': 'Inventory/Inventory',
    'author': 'Prudhvi Inumarthi',
    'website': 'https://github.com/pudhi99',
    'license': 'LGPL-3',
    'price': 14.99,
    'currency': 'USD',
    'support': 'prudhvi.inumarthi99@gmail.com',
    'depends': [
        'base',
        'stock',
        'product_expiry',
        'mail',
    ],
    'data': [
        'security/expiry_security.xml',
        'security/ir.model.access.csv',
        'data/default_config.xml',
        'data/mail_templates.xml',
        'data/ir_cron_data.xml',
        'views/expiry_config_views.xml',
        'views/expiry_dashboard_views.xml',
        'views/stock_lot_views.xml',
        'views/stock_picking_views.xml',
        'views/expiry_history_views.xml',
        'views/expiry_cost_report_views.xml',
        'views/wizard/expiry_bulk_transfer_views.xml',
        'views/wizard/expiry_send_alert_views.xml',
        'views/wizard/expiry_export_views.xml',
        'views/menus.xml',
        'reports/expiry_report_template.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'images': [
        'static/description/banner.png',
        'static/description/feature_overview.png',
    ],
}
